# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Makany' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Makany

  target 'MakanyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MakanyUITests' do
    # Pods for testing
  end
pod 'RealmSwift'

end
